export type WebsiteType = {
    name: string
    url: string
    color: string
    palette?: string[]
    bannerPath: string
    faviconPath: string
    description: string
}

export const websites: WebsiteType[] = [
    {
        bannerPath: '/websites/banners/segment.png',
        color: '#5cc09b',
        description: 'Customer Data Platform',
        faviconPath: '/websites/favicons/segment.png',
        name: 'Segment',
        palette: ['#5cc09b', '#211e32', '#faf8fd'],
        url: 'https://segment.com/',
    },
    {
        bannerPath: '/websites/banners/strapi.png',
        color: '#8c4bff',
        description: 'Open-source headless CMS',
        faviconPath: '/websites/favicons/strapi.png',
        name: 'Strapi',
        palette: ['#1c1b7e', '#8c4bff', '#fee895', '#fd798c', '#80ebff'],
        url: 'https://strapi.io/',
    },
    {
        bannerPath: '/websites/banners/expo.png',
        color: '#a852dc',
        description: 'Open-source platform for building cross-platform applications',
        faviconPath: '/websites/favicons/expo.png',
        name: 'Expo',
        palette: ['#191936', '#0086fc', '#d957d9', '#7f6df3', '#4630eb'],
        url: 'https://expo.io/',
    },
    {
        bannerPath: '/websites/banners/canny.png',
        color: '#969dfa',
        description: 'Customer feedback platform',
        faviconPath: '/websites/favicons/canny.png',
        name: 'Canny',
        palette: ['#6dd345', '#f8f8fa', '#969dfa', '#4753c6', '#3d498d'],
        url: 'https://canny.io/',
    },
    {
        bannerPath: '/websites/banners/shuffle.png',
        color: '#3758f9',
        description: 'Online UI Editor',
        faviconPath: '/websites/favicons/shuffle.png',
        name: 'Shuffle',
        palette: ['#3758f9', '#8d1afc', '#00b0ff', '#00d1b2', '#18b9d1', '#ff8577', '#ffc100', '#f6faff'],
        url: 'https://shuffle.dev/',
    },
    {
        bannerPath: '/websites/banners/anydo.png',
        color: '#0083ff',
        description: 'Task manager',
        faviconPath: '/websites/favicons/anydo.png',
        name: 'Any.do',
        palette: ['#0083ff', '#ebebeb', '#8c23aa', '#6b66cf', '#ffae26', '#f60350'],
        url: 'https://www.any.do/',
    },
    {
        bannerPath: '/websites/banners/miro.png',
        color: '#4262ff',
        description: 'Collaboration whiteboard',
        faviconPath: '/websites/favicons/miro.png',
        name: 'Miro',
        palette: ['#4262ff', '#9d28b2', '#ff9900', '#3e4eb8', '#009788', '#ffd02f', '#050038'],
        url: 'https://miro.com/',
    },
    {
        bannerPath: '/websites/banners/stackshare.png',
        color: '#068dfe',
        description: 'Software discovery and management platform',
        faviconPath: '/websites/favicons/stackshare.png',
        name: 'Stackshare',
        palette: ['#068dfe', '#f7f9fa', '#ffa90a', '#ff7e3f'],
        url: 'https://stackshare.io/',
    },
    {
        bannerPath: '/websites/banners/chromatic.png',
        color: '#1ea7fd',
        description: 'UI development collaboration and feedback platform',
        faviconPath: '/websites/favicons/chromatic.png',
        name: 'Chromatic',
        palette: ['#1ea7fd', '#282c35', '#fc521f', '#ffae00', '#37d5d3', '#6f2cac', '#66bf3c', '#b284dc'],
        url: 'https://www.chromatic.com/',
    },
    {
        bannerPath: '/websites/banners/textemall.png',
        color: '#ff4a29',
        description: 'Mass text messaging and automated calling',
        faviconPath: '/websites/favicons/textemall.png',
        name: 'Text Em All',
        palette: ['#ff4a29', '#32dcf3', '#ffffff', '#2e405d', '#ffc531', '#a7261e', '#2da3a8'],
        url: 'https://www.text-em-all.com/',
    },
    {
        bannerPath: '/websites/banners/netlify.png',
        color: '#15847d',
        description: 'Hosting platform',
        faviconPath: '/websites/favicons/netlify.png',
        name: 'Netlify',
        palette: ['#ff4a29', '#7c0c64', '#e8114e', '#ffffff', '#dc3891', '#2dcdff', '#146396', '#01ad9f'],
        url: 'https://www.netlify.com/',
    },
    {
        bannerPath: '/websites/banners/storybook.png',
        color: '#ff4785',
        description: 'Open-source tool for developing UI components in isolation',
        faviconPath: '/websites/favicons/storybook.png',
        name: 'Storybook',
        palette: ['#ff4785', '#66bf3c', '#4bd9d7', '#1ea7fd', '#f6f9fc', '#333333'],
        url: 'https://storybook.js.org/',
    },
    {
        bannerPath: '/websites/banners/buymeacoffee.png',
        color: '#fd0',
        description: 'Simple, meaningful way to fund your creative work',
        faviconPath: '/websites/favicons/buymeacoffee.png',
        name: 'Buy Me a Coffee',
        palette: ['#fd0', '#0d0c22', '#faf7f2', '#ed7ea6', '#4db7c6', '#f7ba56', '#5e7fff'],
        url: 'https://www.buymeacoffee.com/',
    },
    {
        bannerPath: '/websites/banners/blinkist.png',
        color: '#2cde80',
        description: 'Book-summarizing subscription service',
        faviconPath: '/websites/favicons/blinkist.png',
        name: 'Blinkist',
        palette: ['#2cde80', '#03314b', '#0365f2', '#f1f6f4', '#d7e9ff'],
        url: 'https://www.blinkist.com/',
    },
    {
        bannerPath: '/websites/banners/stripe.png',
        color: '#424770',
        description: 'Financial services and software as a service company',
        faviconPath: '/websites/favicons/stripe.png',
        name: 'Stripe',
        palette: ['#424770', '#87bbfd', '#6772e5', '#87bbfd', '#f6f9fc', '#db78dd', '#3ecf8e', '#f0b64b'],
        url: 'https://stripe.com/',
    },
    {
        bannerPath: '/websites/banners/klientboost.png',
        color: '#6adaf7',
        description: 'Marketing agency',
        faviconPath: '/websites/favicons/klientboost.png',
        name: 'Klientboost',
        palette: ['#6adaf7', '#ff5056', '#fafafa', '#00c853', '#f89d81', '#fcc066', '#515979', '#bad2e1'],
        url: 'https://klientboost.com/',
    },
    {
        bannerPath: '/websites/banners/pauza.png',
        color: '#ed2e2e',
        description: 'Food delivery service',
        faviconPath: '/websites/favicons/pauza.png',
        name: 'Pauza',
        palette: ['#ed2e2e', '#333333', '#ffc200', '#f7f7f7', '#00bc8b'],
        url: 'https://www.pauza.hr/',
    },
    {
        bannerPath: '/websites/banners/atom.png',
        color: '#ffd152',
        description: 'Text editor',
        faviconPath: '/websites/favicons/atom.png',
        name: 'Atom',
        palette: ['#ffd152', '#584b4f', '#343233', '#c13f21', '#d36e2d', '#dda032', '#78af9f', '#659cc8'],
        url: 'https://atom.io/',
    },
    {
        bannerPath: '/websites/banners/invoca.png',
        color: '#02b388',
        description: 'AI-powered call tracking and conversational analytics company',
        faviconPath: '/websites/favicons/invoca.png',
        name: 'Invoca',
        palette: ['#02b388', '#f1fff8', '#010878', '#ffa64d', '#000000', '#f2f7fe', '#fff8f2', '#0e3448'],
        url: 'https://www.invoca.com/',
    },
    {
        bannerPath: '/websites/banners/sproutsocial.png',
        color: '#0ca750',
        description: 'Social media management platform',
        faviconPath: '/websites/favicons/sproutsocial.png',
        name: 'Sprout Social',
        palette: ['#0ca750', '#002138', '#026661', '#08c4b2', '#2079c3', '#ffc618', '#ec4979', '#f3f4f4'],
        url: 'https://sproutsocial.com/',
    },
]
